# coding: utf-8

"""
    Заказ ресурсов в облаке

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cloud import Cloud  # noqa: E501
from swagger_client.rest import ApiException


class TestCloud(unittest.TestCase):
    """Cloud unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCloud(self):
        """Test Cloud"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cloud.Cloud()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
